robot.plugin.group = rcx

robot.program.toolbox.beginner = /ev3.program.toolbox.beginner.xml
robot.program.toolbox.expert = /ev3.program.toolbox.expert.xml
robot.program.default = /ev3.program.default.xml
robot.program.default.nn = /ev3.program.default.nn.xml
robot.configuration.toolbox = /ev3.configuration.toolbox.xml
robot.configuration.default = /ev3.configuration.default.xml
robot.configuration = true
robot.configuration.type = old-S
robot.configuration.old.toplevelblock = robBrick_EV3-Brick

robot.multisim = false

robot.nn = selectable
robot.nn.activations = linear,relu,tanh,sigmoid,bool
robot.class.textlyJava = de.fhg.iais.roberta.textlyJava.Ev3TextlyJavaVisitor

robot.plugin.compiler.resources.dir = RobotEV3/crossCompilerResources/
robot.plugin.update.dir = RobotEV3/updateResources/ev3dev/
robot.plugin.fileExtension.source = py
robot.plugin.fileExtension.binary = py

robot.real.name = Lego RCX
robot.vendor = Lego
robot.info.en = 

robot.helperMethods = classpath:/ev3dev.methods.yml
robot.plugin.worker.validate.and.collect = de.fhg.iais.roberta.worker.validate.Ev3ValidatorAndCollectorWorker
robot.plugin.worker.validate.and.collect.sim = de.fhg.iais.roberta.worker.validate.Ev3SimValidatorAndCollectorWorker
robot.plugin.worker.typecheck = de.fhg.iais.roberta.worker.validate.Ev3TypecheckWorker
robot.plugin.worker.generate = de.fhg.iais.roberta.worker.codegen.Ev3PythonGeneratorWorker
robot.plugin.worker.setup = de.fhg.iais.roberta.worker.CompilerSetupWorker
robot.plugin.worker.save = de.fhg.iais.roberta.worker.SaveWorker
robot.plugin.worker.transfer = de.fhg.iais.roberta.worker.TransferWorker
robot.plugin.worker.generatesimulation = de.fhg.iais.roberta.worker.codegen.Ev3StackMachineGeneratorWorker
robot.plugin.worker.regenerateNepo = de.fhg.iais.roberta.worker.codegen.Ev3RegenerateNepoWorker

robot.plugin.workflow.showsource = validate.and.collect,typecheck,generate,regenerateNepo
robot.plugin.workflow.compile = validate.and.collect,typecheck,generate,setup,save,regenerateNepo
robot.plugin.workflow.run = validate.and.collect,typecheck,generate,setup,save,regenerateNepo,transfer
robot.plugin.workflow.getsimulationcode = validate.and.collect.sim,typecheck,generatesimulation,regenerateNepo
robot.plugin.workflow.runnative = setup,save,transfer
robot.plugin.workflow.compilenative = setup,save
