define(["require", "exports"], function (require, exports) {
    Object.defineProperty(exports, "__esModule", { value: true });
    exports.PYTHON_TEMPLATES = [
        {
            title: "Hello World",
            description: "A simple program that prints Hello World to the console.",
            pythonCode: "import hal\nimport time\n\nhal.init()\nprint('Hello, world!')\n",
            xml: "<export xmlns=\"http://de.fhg.iais.roberta.blockly\"><program><block_set xmlns=\"http://de.fhg.iais.roberta.blockly\" robottype=\"ev3\" xmlversion=\"3.1\" description=\"\" tags=\"\"><instance x=\"384\" y=\"50\"><block type=\"robControls_start\" id=\"Ksoc{L-Z:1,?:`A:1?y\" intask=\"true\" deletable=\"false\"><field name=\"DEBUG\">FALSE</field></block><block type=\"robActions_display_text\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><value name=\"OUT\"><block type=\"text\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><field name=\"TEXT\">Hello, world!</field></block></value><value name=\"COL\"><block type=\"math_number\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><field name=\"NUM\">0</field></block></value><value name=\"ROW\"><block type=\"math_number\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><field name=\"NUM\">0</field></block></value></block></instance></block_set></program><config><block_set xmlns=\"http://de.fhg.iais.roberta.blockly\" robottype=\"ev3\" xmlversion=\"3.1\" description=\"\" tags=\"\"><instance x=\"213\" y=\"213\"><block type=\"robBrick_EV3-Brick\" id=\"1\" intask=\"true\" deletable=\"false\"><field name=\"WHEEL_DIAMETER\">5.6</field><field name=\"TRACK_WIDTH\">18</field><value name=\"S1\"><block type=\"robBrick_touch\" id=\"2\" intask=\"true\"/></value><value name=\"S4\"><block type=\"robBrick_ultrasonic\" id=\"3\" intask=\"true\"/></value><value name=\"MB\"><block type=\"robBrick_motor_big\" id=\"4\" intask=\"true\"><field name=\"MOTOR_REGULATION\">TRUE</field><field name=\"MOTOR_REVERSE\">OFF</field><field name=\"MOTOR_DRIVE\">RIGHT</field></block></value><value name=\"MC\"><block type=\"robBrick_motor_big\" id=\"5\" intask=\"true\"><field name=\"MOTOR_REGULATION\">TRUE</field><field name=\"MOTOR_REVERSE\">OFF</field><field name=\"MOTOR_DRIVE\">LEFT</field></block></value></block></instance></block_set></config></export>"
        },
        {
            title: "Drive Forward",
            description: "Drive the robot forward for 2 seconds.",
            pythonCode: "import hal\nimport time\n\nhal.init()\nhal.driveDistance(20, 30)\n",
            xml: "<export xmlns=\"http://de.fhg.iais.roberta.blockly\"><program><block_set xmlns=\"http://de.fhg.iais.roberta.blockly\" robottype=\"ev3\" xmlversion=\"3.1\" description=\"\" tags=\"\"><instance x=\"384\" y=\"50\"><block type=\"robControls_start\" id=\"Ksoc{L-Z:1,?:`A:1?y\" intask=\"true\" deletable=\"false\"><field name=\"DEBUG\">FALSE</field></block><block type=\"robActions_motorDiff_on_for\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><field name=\"DIRECTION\">FOREWARD</field><value name=\"POWER\"><block type=\"math_number\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><field name=\"NUM\">30</field></block></value><value name=\"DISTANCE\"><block type=\"math_number\" id=\"r?60?_`?`^t?`?`?`?`?\" intask=\"true\"><field name=\"NUM\">20</field></block></value></block></instance></block_set></program><config><block_set xmlns=\"http://de.fhg.iais.roberta.blockly\" robottype=\"ev3\" xmlversion=\"3.1\" description=\"\" tags=\"\"><instance x=\"213\" y=\"213\"><block type=\"robBrick_EV3-Brick\" id=\"1\" intask=\"true\" deletable=\"false\"><field name=\"WHEEL_DIAMETER\">5.6</field><field name=\"TRACK_WIDTH\">18</field><value name=\"S1\"><block type=\"robBrick_touch\" id=\"2\" intask=\"true\"/></value><value name=\"S4\"><block type=\"robBrick_ultrasonic\" id=\"3\" intask=\"true\"/></value><value name=\"MB\"><block type=\"robBrick_motor_big\" id=\"4\" intask=\"true\"><field name=\"MOTOR_REGULATION\">TRUE</field><field name=\"MOTOR_REVERSE\">OFF</field><field name=\"MOTOR_DRIVE\">RIGHT</field></block></value><value name=\"MC\"><block type=\"robBrick_motor_big\" id=\"5\" intask=\"true\"><field name=\"MOTOR_REGULATION\">TRUE</field><field name=\"MOTOR_REVERSE\">OFF</field><field name=\"MOTOR_DRIVE\">LEFT</field></block></value></block></instance></block_set></config></export>"
        }
    ];
});
