robot.plugin.fileExtension.source = json
robot.plugin.fileExtension.binary = json
robot.program.toolbox.beginner = /apitor/program.toolbox.xml
robot.program.toolbox.expert = /apitor/program.toolbox.expert.xml
robot.program.default = /apitor/program.default.xml
robot.configuration.toolbox = /apitor/configuration.toolbox.xml
robot.configuration.default = /apitor/configuration.default.xml
robot.real.name = Apitor Robot X
robot.vendor = Apitor
robot.announcement = beta
robot.configuration = true
robot.configuration.type = new

robot.plugin.worker.validate.and.collect = de.fhg.iais.roberta.worker.apitor.ApitorValidatorAndCollectorWorker
robot.plugin.worker.validate.and.collect.sim = de.fhg.iais.roberta.worker.apitor.ApitorValidatorAndCollectorWorker
robot.plugin.worker.generatesimulation = de.fhg.iais.roberta.worker.apitor.ApitorStackMachineGeneratorWorker
robot.plugin.worker.regenerateNepo = de.fhg.iais.roberta.worker.RegenerateNepoWorker

robot.plugin.workflow.run = validate.and.collect,generatesimulation,regenerateNepo
robot.plugin.workflow.showsource = validate.and.collect.sim,generatesimulation,regenerateNepo
robot.plugin.workflow.getsimulationcode = do.nothing
