define(["require", "exports"], (function (e, n) {
    var t, i, s; Object.defineProperty(n, "__esModule", { value: !0 }), n.setCodeLanguage = n.setViewCode = n.setEditorCode = n.getEditorCode = n.setWasEditedByUser = n.getCurrentLanguage = n.wasEditedByUser = n.init = void 0; var o = !1, a = 0, r = !1;

    // EV3dev API Autocomplete Completer
    var ev3devCompleter = { getCompletions: function (e, n, t, i, s) { var o = [{ caption: "hal.drawText", value: "hal.drawText(text, x, y)", meta: "EV3dev Display", score: 1000 }, { caption: "hal.drawPicture", value: "hal.drawPicture(picture, x, y)", meta: "EV3dev Display", score: 1000 }, { caption: "hal.clearDisplay", value: "hal.clearDisplay()", meta: "EV3dev Display", score: 1000 }, { caption: "hal.waitFor", value: "hal.waitFor(ms)", meta: "EV3dev Timing", score: 1000 }, { caption: "hal.rotateDirectionRegulated", value: "hal.rotateDirectionRegulated(port, direction, speed)", meta: "EV3dev Motor", score: 1000 }, { caption: "hal.rotateDirectionAngle", value: "hal.rotateDirectionAngle(port, direction, speed, angle)", meta: "EV3dev Motor", score: 1000 }, { caption: "hal.turnOnRegulatedMotor", value: "hal.turnOnRegulatedMotor(port, speed)", meta: "EV3dev Motor", score: 1000 }, { caption: "hal.setRegulatedMotorSpeed", value: "hal.setRegulatedMotorSpeed(port, speed)", meta: "EV3dev Motor", score: 1000 }, { caption: "hal.stopMotor", value: "hal.stopMotor(port, mode)", meta: "EV3dev Motor", score: 1000 }, { caption: "hal.isKeyPressed", value: "hal.isKeyPressed(key)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.isPressed", value: "hal.isPressed(port)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.getUltraSonicSensorDistance", value: "hal.getUltraSonicSensorDistance(port)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.getColorSensorColour", value: "hal.getColorSensorColour(port)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.getColorSensorRed", value: "hal.getColorSensorRed(port)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.getGyroSensorAngle", value: "hal.getGyroSensorAngle(port)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.getInfraredSensorDistance", value: "hal.getInfraredSensorDistance(port)", meta: "EV3dev Sensor", score: 1000 }, { caption: "hal.playTone", value: "hal.playTone(frequency, duration)", meta: "EV3dev Sound", score: 1000 }, { caption: "hal.playFile", value: "hal.playFile(filename)", meta: "EV3dev Sound", score: 1000 }, { caption: "hal.ledOn", value: "hal.ledOn(color, mode)", meta: "EV3dev LED", score: 1000 }, { caption: "hal.ledOff", value: "hal.ledOff()", meta: "EV3dev LED", score: 1000 }]; s(null, o) } };

    function c(e) { e.session.setUseWrapMode(!0), e.setShowPrintMargin(!1) } function u(e) { e.setHighlightActiveLine(!1), 0 == e.getSelectedText().length && e.setHighlightActiveLine(!0) } function g(e) { var n = 0; return e.session.getAllFolds().forEach((function (e) { var t = e.start.row, i = e.end.row; n += i - t })), e.session.getLength() - n } function d(e) { for (var n in e.session.getMarkers(!1)) e.session.removeMarker(Number(n)); for (var t = 0; t < g(e); t++)t % 2 == 1 ? (e.session.addGutterDecoration(t, "ace_lineBackgroundGrey"), e.session.highlightLines(t, t, "ace_lineBackgroundGrey", !1)) : e.session.highlightLines(t, t, "ace_lineBackgroundWhite", !1) } n.init = function () { if (!r) { r = !0, ace.require("ace/ext/language_tools"), c(t = ace.edit("codeContent")), t.setOptions({ readOnly: !1, highlightActiveLine: !0, highlightGutterLine: !0, enableBasicAutocompletion: !0, enableSnippets: !0, enableLiveAutocompletion: !0 }); var e = ace.require("ace/ext/language_tools"); e.addCompleter(ev3devCompleter), c(i = ace.edit("aceEditor")), i.setOptions({ enableBasicAutocompletion: !0, enableSnippets: !0, enableLiveAutocompletion: !0 }); var n = ace.require("ace/ext/language_tools"); n.addCompleter(ev3devCompleter), i.session.on("change", (function () { a !== i.session.getLength() && (a = i.session.getLength(), u(i)), o = !0 })), i.session.on("changeFold", (function () { u(i) })), i.selection.on("changeSelection", (function () { u(i) })), t.session.on("changeFold", (function () { d(t) })), $(window).resize((function () { t.resize(), i.resize() })) } }, n.wasEditedByUser = function () { return o }, n.getCurrentLanguage = function () { return s }, n.setWasEditedByUser = function (e) { o = e }, n.getEditorCode = function () { return i.getValue() }, n.setEditorCode = function (e) { i.setValue(e, 0), i.clearSelection(), i.focus(), u(i) }, n.setViewCode = function (e) { t.setValue(e, 0), t.clearSelection(), t.moveCursorTo(0, 0), d(t) }, n.setCodeLanguage = function (e) { var n; switch (e) { case "py": default: n = "python"; break; case "java": n = "java"; break; case "ino": case "nxc": case "cpp": n = "c_cpp"; break; case "json": n = "json" }i.session.setMode("ace/mode/" + n), t.session.setMode("ace/mode/" + n), a = i.session.getLength(), s = n }
}));
//# sourceMappingURL=aceEditor.js.map
//# sourceMappingURL=aceEditor.js.map
