package de.fhg.iais.roberta.util.jaxb;

import java.io.InputStream;
import java.io.StringReader;
import java.io.StringWriter;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

import javax.xml.XMLConstants;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.Unmarshaller;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;
import javax.xml.transform.sax.SAXSource;
import javax.xml.transform.stream.StreamSource;
import javax.xml.validation.Schema;
import javax.xml.validation.SchemaFactory;

import org.apache.commons.io.IOUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.XMLReader;

import de.fhg.iais.roberta.blockly.generated.Block;
import de.fhg.iais.roberta.blockly.generated.BlockSet;
import de.fhg.iais.roberta.blockly.generated.Hide;
import de.fhg.iais.roberta.util.dbc.DbcException;

public class JaxbHelper {
    private static final Logger LOG = LoggerFactory.getLogger(JaxbHelper.class);
    private static final String DISALLOW_DOCTYPE_DECL = "http://apache.org/xml/features/disallow-doctype-decl";
    private static final String EXTERNAL_GENERAL_ENTITIES = "http://xml.org/sax/features/external-general-entities";
    private static final String EXTERNAL_PARAMETER_ENTITIES = "http://xml.org/sax/features/external-parameter-entities";
    private static final String LOAD_EXTERNAL_DTD = "http://apache.org/xml/features/nonvalidating/load-external-dtd";

    private static final Schema blockSetSchema;
    private static final JAXBContext jaxbContext;
    private static final Map<Class<?>, JAXBContext> jaxbContexts = new ConcurrentHashMap<>();
    static {
        try {
            SchemaFactory sf = SchemaFactory.newInstance(XMLConstants.W3C_XML_SCHEMA_NS_URI);
            sf.setProperty(XMLConstants.ACCESS_EXTERNAL_DTD, "");
            sf.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
            InputStream xsdStream = JaxbHelper.class.getResourceAsStream("/blockly.xsd");
            StreamSource xsdSource = new StreamSource(xsdStream);
            blockSetSchema = sf.newSchema(xsdSource);
            jaxbContext = JAXBContext.newInstance(BlockSet.class);
            jaxbContexts.put(BlockSet.class, jaxbContext);
        } catch ( Exception e ) {
            LOG.error("1. from blockly.xsd no schema could be generated or 2. JAXBContext could not be created", e);
            throw new RuntimeException("from blockly.xsd no schema could be generated");
        }
    }

    private JaxbHelper() {
        // no objects
    }

    /**
     * return the BlockSet generated by a jaxb unmarshaller for a given blockly XML string.
     *
     * @param blocklyXml the blockly XML as String
     * @return the BlockSet instance corresponding to the XML
     */
    public static BlockSet xml2BlockSet(String blocklyXml) throws JAXBException {
        Unmarshaller jaxbUnmarshaller = jaxbContext.createUnmarshaller();
        jaxbUnmarshaller.setSchema(blockSetSchema);
        return (BlockSet) jaxbUnmarshaller.unmarshal(createSecureSaxSource(blocklyXml));
    }

    /**
     * return the element of type T generated by an jaxb unmarshaller for a given blockly XML string.<br>
     * <b>This call is expensive. Use it not too often. It is ok to use it for the import/export of XML, for example.</b>
     *
     * @param xml the XML as String
     * @param clazz the element class, an object of which should be returned
     * @return the element instance corresponding to the XML
     */
    @SuppressWarnings("unchecked")
    public static <T> T xml2Element(String xml, Class<T> clazz) throws JAXBException {
        Unmarshaller jaxbUnmarshaller = getJaxbContext(clazz).createUnmarshaller();
        jaxbUnmarshaller.setSchema(blockSetSchema);
        return (T) jaxbUnmarshaller.unmarshal(createSecureSaxSource(xml));
    }

    static JAXBContext getJaxbContext(Class<?> clazz) throws JAXBException {
        JAXBContext cachedContext = jaxbContexts.get(clazz);
        if ( cachedContext != null ) {
            return cachedContext;
        }
        synchronized ( jaxbContexts ) {
            cachedContext = jaxbContexts.get(clazz);
            if ( cachedContext == null ) {
                cachedContext = JAXBContext.newInstance(clazz);
                jaxbContexts.put(clazz, cachedContext);
            }
            return cachedContext;
        }
    }

    private static SAXSource createSecureSaxSource(String xml) throws JAXBException {
        try {
            SAXParserFactory parserFactory = SAXParserFactory.newInstance();
            parserFactory.setNamespaceAware(true);
            parserFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);
            parserFactory.setFeature(DISALLOW_DOCTYPE_DECL, true);
            parserFactory.setFeature(EXTERNAL_GENERAL_ENTITIES, false);
            parserFactory.setFeature(EXTERNAL_PARAMETER_ENTITIES, false);
            parserFactory.setFeature(LOAD_EXTERNAL_DTD, false);

            XMLReader xmlReader = parserFactory.newSAXParser().getXMLReader();
            xmlReader.setProperty(XMLConstants.ACCESS_EXTERNAL_DTD, "");
            xmlReader.setProperty(XMLConstants.ACCESS_EXTERNAL_SCHEMA, "");
            return new SAXSource(xmlReader, new InputSource(new StringReader(xml)));
        } catch ( ParserConfigurationException | SAXException e ) {
            throw new JAXBException("Could not create a secure XML parser", e);
        }
    }

    /**
     * return the XML generated by a jaxb marshaller for a given BlockSet.
     *
     * @param blockSet the BlockSet from which XML has to be generated for
     * @return the XML as a String
     * @throws Exception
     */
    public static String blockSet2xml(BlockSet blockSet) throws Exception {
        Marshaller jaxbmarshaller = jaxbContext.createMarshaller();
        jaxbmarshaller.setProperty("com.sun.xml.bind.xmlDeclaration", Boolean.FALSE);
        jaxbmarshaller.setSchema(blockSetSchema);
        StringWriter writer = new StringWriter();
        jaxbmarshaller.marshal(blockSet, writer);
        return writer.toString();
    }

    /**
     * return the BlockSet generated by a jaxb unmarshaller for a file-path to blockly XML.
     *
     * @param pathToblocklyXml the file path to a blockly XML
     * @return the BlockSet instance corresponding to the XML
     * @throws Exception
     */
    public static BlockSet path2BlockSet(String pathToblocklyXml) throws Exception {
        return xml2BlockSet(IOUtils.toString(JaxbHelper.class.getResourceAsStream(pathToblocklyXml), "UTF-8"));
    }

    public static Hide getHideFromBlock(Block block) {
        List<Hide> hide = block.getHide();
        if ( hide == null || hide.size() == 0 ) {
            return null;
        } else if ( hide.size() == 1 ) {
            return hide.get(0);
        } else {
            throw new DbcException("more than 1 hide element");
        }
    }

}
