name: IntegrationTest-Dispatch-By-User

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch/ref for integration tests'
        required: true
        default: 'develop'
        type: string
      oraccrsctag:
        description: 'Tag/version for the crosscompiler resources'
        required: true
        default: 'latest'
        type: string

permissions:
  contents: read

jobs:
  integration-test:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    container: openroberta/base-x64:${{ inputs.oraccrsctag }}
    steps:
      - name: branch ${{ inputs.branch }}, repo ${{ github.repository }}, ora-cc-rsc-tag ${{ inputs.oraccrsctag }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          persist-credentials: false
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v4
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven and run integration tests
        run: mvn --batch-mode clean install -PrunIT
