name: CodeON unit tests

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master, develop ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 45
    steps:
      - name: Checkout branch ${{ github.ref }} of repo ${{ github.repository }}
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Java JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Cache local maven repository
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test active CodeON robot reactor
        run: mvn --batch-mode -pl OpenRobertaRobot,RobotEdison,RobotSpike,RobotCozmo,RobotApitor,RobotRCX -am -DargLine='--add-opens java.base/java.lang=ALL-UNNAMED' test
      - name: Package CodeON server reactor
        run: mvn --batch-mode -pl OpenRobertaServer -am -DskipTests package
